# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-07 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(blank=True, default='', max_length=200)),
                ('airdate', models.CharField(blank=True, default='', max_length=200)),
                ('end_airdate', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ('ids',),
            },
        ),
    ]
