# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-08 08:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
