# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-13 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets1', '0002_snippet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='content',
            field=jsonfield.fields.JSONField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='snippet',
            name='operation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='snippet',
            name='ref',
            field=jsonfield.fields.JSONField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='snippet',
            name='resource',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='snippet',
            name='source',
            field=jsonfield.fields.JSONField(blank=True, default=''),
        ),
    ]
