# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-24 06:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets1', '0005_snippet2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(blank=True, default='', max_length=200)),
                ('operation', models.CharField(blank=True, default='', max_length=200)),
                ('ref', jsonfield.fields.JSONField(blank=True, default='')),
                ('airdate', models.CharField(blank=True, default='', max_length=200)),
                ('end_airdate', models.CharField(blank=True, default='', max_length=200)),
                ('content', jsonfield.fields.JSONField(blank=True, default='')),
                ('source', jsonfield.fields.JSONField(blank=True, default='')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
